version: "3.9"

services:
  server:
    container_name: server
    build:
      context: ./
      dockerfile: DockerFile
    ports:
      - "3000:3000"
    environment:
      DB_HOST: localhost
      DB_PORT: 27017
      DB_DATABASE: dev
    volumes:
      - ./:/app
      - /app/node_modules
    restart: "unless-stopped"
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
